// This file is generated by scripts/build.ts
// Do not edit this file directly
export const absolutePosition: { body: string; width: number; height: number; };

export const alignStretch: { body: string; width: number; height: number; };

export const angle: { body: string; width: number; height: number; };

export const braces: { body: string; width: number; height: number; };

export const branch: { body: string; width: number; height: number; };

export const button: { body: string; width: number; height: number; };

export const checkBox: { body: string; width: number; height: number; };

export const chevrons: { body: string; width: number; height: number; };

export const codeEditor: { body: string; width: number; height: number; };

export const component: { body: string; width: number; height: number; };

export const dashedLine: { body: string; width: number; height: number; };

export const dottedLine: { body: string; width: number; height: number; };

export const edgeAll: { body: string; width: number; height: number; };

export const edgeBottom: { body: string; width: number; height: number; };

export const edgeLeft: { body: string; width: number; height: number; };

export const edgeRight: { body: string; width: number; height: number; };

export const edgeTop: { body: string; width: number; height: number; };

export const fillArea: { body: string; width: number; height: number; };

export const fixedSize: { body: string; width: number; height: number; };

export const frame: { body: string; width: number; height: number; };

export const group: { body: string; width: number; height: number; };

export const hStack: { body: string; width: number; height: number; };

export const heading: { body: string; width: number; height: number; };

export const hugContents: { body: string; width: number; height: number; };

export const image: { body: string; width: number; height: number; };

export const inlineBlock: { body: string; width: number; height: number; };

export const input: { body: string; width: number; height: number; };

export const instance: { body: string; width: number; height: number; };

export const italic: { body: string; width: number; height: number; };

export const justifyCenter: { body: string; width: number; height: number; };

export const justifyEnd: { body: string; width: number; height: number; };

export const justifySpaceBetween: { body: string; width: number; height: number; };

export const justifyStart: { body: string; width: number; height: number; };

export const lineEdit: { body: string; width: number; height: number; };

export const linearGradientRect: { body: string; width: number; height: number; };

export const marginBottom: { body: string; width: number; height: number; };

export const marginLeft: { body: string; width: number; height: number; };

export const marginRight: { body: string; width: number; height: number; };

export const marginTop: { body: string; width: number; height: number; };

export const margin: { body: string; width: number; height: number; };

export const noItalic: { body: string; width: number; height: number; };

export const padding: { body: string; width: number; height: number; };

export const paragraphNoBorder: { body: string; width: number; height: number; };

export const paragraph: { body: string; width: number; height: number; };

export const position: { body: string; width: number; height: number; };

export const radialGradientRect: { body: string; width: number; height: number; };

export const radioButton: { body: string; width: number; height: number; };

export const radius: { body: string; width: number; height: number; };

export const rect: { body: string; width: number; height: number; };

export const relativePosition: { body: string; width: number; height: number; };

export const select: { body: string; width: number; height: number; };

export const separateCorners: { body: string; width: number; height: number; };

export const separateEdges: { body: string; width: number; height: number; };

export const sizeContain: { body: string; width: number; height: number; };

export const sizeCover: { body: string; width: number; height: number; };

export const sizeFill: { body: string; width: number; height: number; };

export const slot: { body: string; width: number; height: number; };

export const solidLine: { body: string; width: number; height: number; };

export const solidRect: { body: string; width: number; height: number; };

export const span: { body: string; width: number; height: number; };

export const staticPosition: { body: string; width: number; height: number; };

export const svg: { body: string; width: number; height: number; };

export const textArea: { body: string; width: number; height: number; };

export const textBox: { body: string; width: number; height: number; };

export const text: { body: string; width: number; height: number; };

export const toggle: { body: string; width: number; height: number; };

export const vStack: { body: string; width: number; height: number; };

export const window: { body: string; width: number; height: number; };